server:
  port: 8080  # Change to your desired port
  

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: auth-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
       properties:
         spring.json.trusted.packages: "*"


